language: python

sudo: false

python:
    - '3.5'

install:
    - pip install --upgrade pip
    - pip install -e ".[testing]"

script:
    - py.test

services:
    - postgresql

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres

env:
    - ""
    - SQLALCHEMY_TEST_DB="postgresql://postgres@localhost/travis_ci_test"

addons:
    postgresql: "9.5"
